### ISSUE TITLE
Getting a tonne of errors on Unity 2018.2.0f2

### ISSUE THREAD

**Issue by ghost** [keijiro/Kino#2]
After downloading the project and running on Unity 2018.2.0f2, the project produces a tonne of errors.
![capture](https://user-images.githubusercontent.com/38675166/48519536-5f4cc900-e8c1-11e8-9a5a-8fe904c4fa64.PNG)

**Comment by Jordy3D** [comment]
Here's a fix for that
Replace:
#include "Packages/com.unity.postprocessing/PostProcessing/Shaders/StdLib.hlsl"
#include "Packages/com.unity.postprocessing/PostProcessing/Shaders/Colors.hlsl"
with:
#include "PostProcessing/Shaders/StdLib.hlsl"
#include "PostProcessing/Shaders/Colors.hlsl"

The path is different now, this works, at the very least for Unity 2018.2.0f2.

**Comment by keijiro** [comment]
@Jordy3D is right. The shader include paths were changed in the recent version of Unity, and it broke the compatibility of these shaders. I updated README as requiring Unity 2018.3.

**Comment by st4rdog** [comment]
I couldn't get any path to work, so I just copied over the .hlsl files from PostProcessing\Shaders (and the API folder) to Kino-upm\Resources and changed the shader paths to #include "StdLib.hlsl".

Overlay and Recolor still don't work.

2018.3.0b2
Post Processing 2.0.17

**Comment by st4rdog** [comment]
I couldn't get any path to work, so I just copied over the .hlsl files from PostProcessing\Shaders (and the API folder) to Kino-upm\Resources and changed the shader to #include "StdLib.hlsl", also the Overlay.hlsl/Recolor.hlsl includes.

2018.3.0b2
Post Processing 2.0.17

**Comment by keijiro** [comment]
The behavior of shader include path was changed during the beta phase, so it requires using the latest version of beta build.

I verified it working correctly on the released version of 2018.3. Now I'm closing this issue. Please feel free to reopen it for further questions.
